/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andev_androidshaderdemo_nativedemo_NativeController */

#ifndef _Included_com_andev_androidshaderdemo_nativedemo_NativeController
#define _Included_com_andev_androidshaderdemo_nativedemo_NativeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andev_androidshaderdemo_nativedemo_NativeController
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_andev_androidshaderdemo_nativedemo_NativeController_init
  (JNIEnv *, jobject);

/*
 * Class:     com_andev_androidshaderdemo_nativedemo_NativeController
 * Method:    setSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_andev_androidshaderdemo_nativedemo_NativeController_setSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_andev_androidshaderdemo_nativedemo_NativeController
 * Method:    resetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_andev_androidshaderdemo_nativedemo_NativeController_resetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_andev_androidshaderdemo_nativedemo_NativeController
 * Method:    showBitmap
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_andev_androidshaderdemo_nativedemo_NativeController_showBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_andev_androidshaderdemo_nativedemo_NativeController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_andev_androidshaderdemo_nativedemo_NativeController_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
